In [ ]:
import pandas as pd
import numpy as np
#Create sample dataframe
df = pd.DataFrame({
    'name': ['John', 'Jane', 'Bob', 'Alice'],
    'department': ['Sales', 'Marketing', 'Sales', 'IT'],
    'salary': [10000,23333,15555,25003],
    'experience':[1,4,2,5]
})
df.dropna()

    name department  salary  experience
0   John      Sales   10000           1
1   Jane  Marketing   23333           4
2    Bob      Sales   15555           2
3  Alice         IT   25003           5

In [ ]:
df.dropna(axis=1)

    name department  salary  experience
0   John      Sales   10000           1
1   Jane  Marketing   23333           4
2    Bob      Sales   15555           2
3  Alice         IT   25003           5

In [ ]:
df.dropna(how='all')

    name department  salary  experience
0   John      Sales   10000           1
1   Jane  Marketing   23333           4
2    Bob      Sales   15555           2
3  Alice         IT   25003           5

In [ ]:
import pandas as pd
import numpy as np
#Create sample dataframe
df = pd.DataFrame({
    'name': ['John', 'Jane', 'Bob', 'Alice'],
    'department': ['Sales', 'Marketing', 'Sales','IT'],
    'salary': [10000,23333,15555,25003],
    'experience':[1,4,2,5]
})
df.isna()

    name  department  salary  experience
0  False       False   False       False
1  False       False   False       False
2  False       False   False       False
3  False       False   False       False

In [ ]:
df.isnull()

    name  department  salary  experience
0  False       False   False       False
1  False       False   False       False
2  False       False   False       False
3  False       False   False       False

In [ ]:
df.isna().sum()

name          0
department    0
salary        0
experience    0
dtype: int64

In [ ]:
df.fillna(0)

    name department  salary  experience
0   John      Sales   10000           1
1   Jane  Marketing   23333           4
2    Bob      Sales   15555           2
3  Alice         IT   25003           5

In [ ]:
df.ffill()

    name department  salary  experience
0   John      Sales   10000           1
1   Jane  Marketing   23333           4
2    Bob      Sales   15555           2
3  Alice         IT   25003           5

In [ ]:
df.fillna({'col1':0,'col2':'unknown'})

    name department  salary  experience
0   John      Sales   10000           1
1   Jane  Marketing   23333           4
2    Bob      Sales   15555           2
3  Alice         IT   25003           5